#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanNET
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QUANNET1")]
	public partial class QuanNetDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRent(Rent instance);
    partial void UpdateRent(Rent instance);
    partial void DeleteRent(Rent instance);
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    partial void InsertComputer(Computer instance);
    partial void UpdateComputer(Computer instance);
    partial void DeleteComputer(Computer instance);
    #endregion
		
		public QuanNetDataContext() : 
				base(global::QuanNET.Properties.Settings.Default.QUANNET1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanNetDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanNetDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanNetDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanNetDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Rent> Rents
		{
			get
			{
				return this.GetTable<Rent>();
			}
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
		
		public System.Data.Linq.Table<Computer> Computers
		{
			get
			{
				return this.GetTable<Computer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rent")]
	public partial class Rent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RentID;
		
		private string _ComputerID;
		
		private string _UserID;
		
		private System.DateTime _RentTimeStart;
		
		private System.Nullable<System.DateTime> _RentTimeEnd;
		
		private System.Nullable<decimal> _TotalMoney;
		
		private EntityRef<Account> _Account;
		
		private EntityRef<Computer> _Computer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRentIDChanging(int value);
    partial void OnRentIDChanged();
    partial void OnComputerIDChanging(string value);
    partial void OnComputerIDChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnRentTimeStartChanging(System.DateTime value);
    partial void OnRentTimeStartChanged();
    partial void OnRentTimeEndChanging(System.Nullable<System.DateTime> value);
    partial void OnRentTimeEndChanged();
    partial void OnTotalMoneyChanging(System.Nullable<decimal> value);
    partial void OnTotalMoneyChanged();
    #endregion
		
		public Rent()
		{
			this._Account = default(EntityRef<Account>);
			this._Computer = default(EntityRef<Computer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RentID
		{
			get
			{
				return this._RentID;
			}
			set
			{
				if ((this._RentID != value))
				{
					this.OnRentIDChanging(value);
					this.SendPropertyChanging();
					this._RentID = value;
					this.SendPropertyChanged("RentID");
					this.OnRentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComputerID", DbType="VarChar(20)")]
		public string ComputerID
		{
			get
			{
				return this._ComputerID;
			}
			set
			{
				if ((this._ComputerID != value))
				{
					if (this._Computer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnComputerIDChanging(value);
					this.SendPropertyChanging();
					this._ComputerID = value;
					this.SendPropertyChanged("ComputerID");
					this.OnComputerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="VarChar(50)")]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._Account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RentTimeStart", DbType="DateTime NOT NULL")]
		public System.DateTime RentTimeStart
		{
			get
			{
				return this._RentTimeStart;
			}
			set
			{
				if ((this._RentTimeStart != value))
				{
					this.OnRentTimeStartChanging(value);
					this.SendPropertyChanging();
					this._RentTimeStart = value;
					this.SendPropertyChanged("RentTimeStart");
					this.OnRentTimeStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RentTimeEnd", DbType="DateTime")]
		public System.Nullable<System.DateTime> RentTimeEnd
		{
			get
			{
				return this._RentTimeEnd;
			}
			set
			{
				if ((this._RentTimeEnd != value))
				{
					this.OnRentTimeEndChanging(value);
					this.SendPropertyChanging();
					this._RentTimeEnd = value;
					this.SendPropertyChanged("RentTimeEnd");
					this.OnRentTimeEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalMoney", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> TotalMoney
		{
			get
			{
				return this._TotalMoney;
			}
			set
			{
				if ((this._TotalMoney != value))
				{
					this.OnTotalMoneyChanging(value);
					this.SendPropertyChanging();
					this._TotalMoney = value;
					this.SendPropertyChanged("TotalMoney");
					this.OnTotalMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Rent", Storage="_Account", ThisKey="UserID", OtherKey="AccountID", IsForeignKey=true)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.Rents.Remove(this);
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.Rents.Add(this);
						this._UserID = value.AccountID;
					}
					else
					{
						this._UserID = default(string);
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Computer_Rent", Storage="_Computer", ThisKey="ComputerID", OtherKey="ComputerID", IsForeignKey=true)]
		public Computer Computer
		{
			get
			{
				return this._Computer.Entity;
			}
			set
			{
				Computer previousValue = this._Computer.Entity;
				if (((previousValue != value) 
							|| (this._Computer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Computer.Entity = null;
						previousValue.Rents.Remove(this);
					}
					this._Computer.Entity = value;
					if ((value != null))
					{
						value.Rents.Add(this);
						this._ComputerID = value.ComputerID;
					}
					else
					{
						this._ComputerID = default(string);
					}
					this.SendPropertyChanged("Computer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Account")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _AccountID;
		
		private string _AccountName;
		
		private string _AccountPassword;
		
		private string _AccountPhone;
		
		private System.Nullable<int> _AccountRole;
		
		private System.Nullable<decimal> _AccountBalance;
		
		private EntitySet<Rent> _Rents;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAccountIDChanging(string value);
    partial void OnAccountIDChanged();
    partial void OnAccountNameChanging(string value);
    partial void OnAccountNameChanged();
    partial void OnAccountPasswordChanging(string value);
    partial void OnAccountPasswordChanged();
    partial void OnAccountPhoneChanging(string value);
    partial void OnAccountPhoneChanged();
    partial void OnAccountRoleChanging(System.Nullable<int> value);
    partial void OnAccountRoleChanged();
    partial void OnAccountBalanceChanging(System.Nullable<decimal> value);
    partial void OnAccountBalanceChanged();
    #endregion
		
		public Account()
		{
			this._Rents = new EntitySet<Rent>(new Action<Rent>(this.attach_Rents), new Action<Rent>(this.detach_Rents));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				if ((this._AccountID != value))
				{
					this.OnAccountIDChanging(value);
					this.SendPropertyChanging();
					this._AccountID = value;
					this.SendPropertyChanged("AccountID");
					this.OnAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string AccountName
		{
			get
			{
				return this._AccountName;
			}
			set
			{
				if ((this._AccountName != value))
				{
					this.OnAccountNameChanging(value);
					this.SendPropertyChanging();
					this._AccountName = value;
					this.SendPropertyChanged("AccountName");
					this.OnAccountNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountPassword", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string AccountPassword
		{
			get
			{
				return this._AccountPassword;
			}
			set
			{
				if ((this._AccountPassword != value))
				{
					this.OnAccountPasswordChanging(value);
					this.SendPropertyChanging();
					this._AccountPassword = value;
					this.SendPropertyChanged("AccountPassword");
					this.OnAccountPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountPhone", DbType="VarChar(10)")]
		public string AccountPhone
		{
			get
			{
				return this._AccountPhone;
			}
			set
			{
				if ((this._AccountPhone != value))
				{
					this.OnAccountPhoneChanging(value);
					this.SendPropertyChanging();
					this._AccountPhone = value;
					this.SendPropertyChanged("AccountPhone");
					this.OnAccountPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountRole", DbType="Int")]
		public System.Nullable<int> AccountRole
		{
			get
			{
				return this._AccountRole;
			}
			set
			{
				if ((this._AccountRole != value))
				{
					this.OnAccountRoleChanging(value);
					this.SendPropertyChanging();
					this._AccountRole = value;
					this.SendPropertyChanged("AccountRole");
					this.OnAccountRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountBalance", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> AccountBalance
		{
			get
			{
				return this._AccountBalance;
			}
			set
			{
				if ((this._AccountBalance != value))
				{
					this.OnAccountBalanceChanging(value);
					this.SendPropertyChanging();
					this._AccountBalance = value;
					this.SendPropertyChanged("AccountBalance");
					this.OnAccountBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Rent", Storage="_Rents", ThisKey="AccountID", OtherKey="UserID")]
		public EntitySet<Rent> Rents
		{
			get
			{
				return this._Rents;
			}
			set
			{
				this._Rents.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Rents(Rent entity)
		{
			this.SendPropertyChanging();
			entity.Account = this;
		}
		
		private void detach_Rents(Rent entity)
		{
			this.SendPropertyChanging();
			entity.Account = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Computer")]
	public partial class Computer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ComputerID;
		
		private string _ComputerName;
		
		private string _ComputerStatus;
		
		private decimal _ComputerMoney;
		
		private EntitySet<Rent> _Rents;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnComputerIDChanging(string value);
    partial void OnComputerIDChanged();
    partial void OnComputerNameChanging(string value);
    partial void OnComputerNameChanged();
    partial void OnComputerStatusChanging(string value);
    partial void OnComputerStatusChanged();
    partial void OnComputerMoneyChanging(decimal value);
    partial void OnComputerMoneyChanged();
    #endregion
		
		public Computer()
		{
			this._Rents = new EntitySet<Rent>(new Action<Rent>(this.attach_Rents), new Action<Rent>(this.detach_Rents));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComputerID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ComputerID
		{
			get
			{
				return this._ComputerID;
			}
			set
			{
				if ((this._ComputerID != value))
				{
					this.OnComputerIDChanging(value);
					this.SendPropertyChanging();
					this._ComputerID = value;
					this.SendPropertyChanged("ComputerID");
					this.OnComputerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComputerName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string ComputerName
		{
			get
			{
				return this._ComputerName;
			}
			set
			{
				if ((this._ComputerName != value))
				{
					this.OnComputerNameChanging(value);
					this.SendPropertyChanging();
					this._ComputerName = value;
					this.SendPropertyChanged("ComputerName");
					this.OnComputerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComputerStatus", DbType="NVarChar(30)")]
		public string ComputerStatus
		{
			get
			{
				return this._ComputerStatus;
			}
			set
			{
				if ((this._ComputerStatus != value))
				{
					this.OnComputerStatusChanging(value);
					this.SendPropertyChanging();
					this._ComputerStatus = value;
					this.SendPropertyChanged("ComputerStatus");
					this.OnComputerStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComputerMoney", DbType="Decimal(18,0) NOT NULL")]
		public decimal ComputerMoney
		{
			get
			{
				return this._ComputerMoney;
			}
			set
			{
				if ((this._ComputerMoney != value))
				{
					this.OnComputerMoneyChanging(value);
					this.SendPropertyChanging();
					this._ComputerMoney = value;
					this.SendPropertyChanged("ComputerMoney");
					this.OnComputerMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Computer_Rent", Storage="_Rents", ThisKey="ComputerID", OtherKey="ComputerID")]
		public EntitySet<Rent> Rents
		{
			get
			{
				return this._Rents;
			}
			set
			{
				this._Rents.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Rents(Rent entity)
		{
			this.SendPropertyChanging();
			entity.Computer = this;
		}
		
		private void detach_Rents(Rent entity)
		{
			this.SendPropertyChanging();
			entity.Computer = null;
		}
	}
}
#pragma warning restore 1591
